### ISSUE TITLE
Command execution problem when more then one space between arguments and / or options

### ISSUE THREAD

**Issue by dirtyren** [ConSol/mod-gearman-worker-go#1]
Hey, I found that if you have more than one space between the arguments and / or options of a plugin, the extra space will be treated as a parameter by exec.CommandContext, at least for one of my PHP plugins.

  I replaced
   splitted := strings.Split(received.commandLine, " ")
  per 
 splitted := strings.Fields(received.commandLine)

   and it solved my problem, as Fields will split one or more spaces.

Should a pull this request ?

   Tks.

**Comment by sni** [comment]
Sounds good. Yes, please create a pull request.

**Comment by sni** [comment]
nevermind, did it already since i wanted to cut off a new release. Thanks for pointing this out.
