### ISSUE TITLE
Service check did not exit properly

### ISSUE THREAD

**Issue by dirtyren** [ConSol/mod-gearman-worker-go#5]
Hello,

I had to go back to the worker in C, I have  some shell plugins returning Service check did not exit properly on the interface.
  I changed the plugin to test to:

   #!/bin/sh
   echo "ok"
   exit 0

   and the behavior persisted.

I could not pin point why this is happening, any ideas? 

  Tks.

**Comment by sni** [comment]
i cannot reproduce that, if i create a plugin like that, it does exactly what expected.

**Comment by dirtyren** [comment]
Found the problema @sni , check the example above, it's missing a ! on #/bin/bash ... :( . The worker in C will run it regardless, but the Go wont.
  Sorry about that, closing the issue.
