### ISSUE TITLE
Worker looses connection to gearmand

### ISSUE THREAD

**Issue by dirtyren** [ConSol/mod-gearman-worker-go#6]
Hello,

I noticed some odd behaviors with the worker in Go on cluster.

1. the node connection to gearmand will disappear sometimes, but the workers to the host and service queues will there and sometimes, each node will have two connections showing, although just one daemon running on each node

2. sometimes the process just dies, no segfaults

3. I have 4 nodes, 3 of them have 50 workers and one 10, so I should have 160 workers max per queue. The daemon died on 3 nodes and gearmand was showing 261 workers available 

  I am using naemon-1.0.8 and gearmand 0.33.

  Tks.

**Comment by sni** [comment]
yes, i noticed that as well, if you run the worker with 2 servers, there seems to be issues with reconnects. I will have a look at that tomorrow.

**Comment by sni** [comment]
fixed with 140a280b5f0046ba30fcea1591bc4a57dcccb350
