### ISSUE TITLE
job_timeout option is ignored

### ISSUE THREAD

**Issue by jstark1** [ConSol/mod-gearman-worker-go#8]
Hi,
we are using mod-gearman-worker-go with OMD 2.90 (also with 3.00). The job_timeout option from etc/mod-gearman/worker.cfg is ignored. 

Option is set to:
job_timeout=120

The Logfile says:
[2019-04-10 17:28:10.850][Trace][worker.go:137]
         type: service
         result_queue: check_results
         host_name: XXXX
         service_description: XXXX
         start_time: 1554910390.000000
         next_check: 1554910390.000000
         core_time: 1554910090.847630
         timeout: 60
         command_line: /omd/sites/stbv/local/lib/nagios/....

best regards,
Jens

**Comment by sni** [comment]
thats on purpose, that timeout is only used if there is no timeout sent within the job data. Basically thats only the case for eventhandlers and notifications.

Quoting from the docs
```
# Default job timeout in seconds. Currently this value is only used for
# eventhandler. The worker will use the values from the core for host and
# service checks.
```

**Comment by jstark1** [comment]
thanks for the explanation. The service_check_timeout option in the tuning.cfg file works as expected.
